push @generated_exts, "fdb_latexmk";
push @generated_exts, "fls";
push @generated_exts, "log";
push @generated_exts, "out";
push @generated_exts, "synctex.gz";
push @generated_exts, "xdv";

$pdflatex = 'pdflatex --shell-escape %O %S';
